modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="cheesepower"

version="1.0" #mandatory

displayName="Cheese Power"

updateJSONURL="http://myurl.me/"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="Mozz(me) is the creator of this mod. A thanks goes out to Darper and ouTPhaze for helping with idea." #optional

authors="Mozz" #optional

description='''
    This is a mod all about cheese! To be more specific its about generating power from cheese!
'''

[[dependencies.cheesepower]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.cheesepower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"